<?php
$lang = [
    // Menú Principal y Navegación
    "titulo_index" => "Cerebro Principal",
    "menu_principal" => "Menú Principal",
    "btn_agenda" => "Agenda",
    "btn_personal" => "Personal",
    "btn_academico" => "Académico",
    "btn_estado_server" => "Estado del servidor",
    "inicio" => "Inicio",
    "volver" => "Atrás",
    // Menú Agenda
    "titulo_agenda_menu" => "Menú de Agenda",
    "menu_acciones" => "Acciones",
    "btn_crear_recordatorio" => "Crear Recordatorio",
    "btn_tareas_pendientes" => "Tareas Pendientes",
    "btn_tareas_completadas" => "Tareas Completadas",
    // Lista de Tareas (Pendientes)
    "titulo_lista" => "Lista de Tareas",
    "tarea" => "Tarea",
    "asignatura" => "Asignatura",
    "estado" => "Estado",
    "acciones" => "Acciones",
    "nueva_tarea" => "+ Nueva Tarea",
    "descripcion" => "Descripción",
    "fecha" => "Fecha",
    "boton_filtrar" => "Filtrar",
    "boton_limpiar" => "Limpiar",
    "buscar_placeholder" => "🔍 Buscar tarea rápidamente por título...",
    // Crear Tarea
    "nueva_tarea_titulo" => "Nueva Tarea",
    "msg_fecha_pasado" => "Error: La fecha no puede estar en el pasado.",
    "msg_tarea_guardada" => "¡Tarea guardada con éxito!",
    "msg_error_db" => "Error de base de datos: ",
    "label_titel" => "Título:",
    "placeholder_titel" => "Ej: Examen de redes...",
    "label_descripcion" => "Descripción:",
    "placeholder_descripcion" => "Añade detalles aquí...",
    "label_fach" => "Asignatura:",
    "label_datum" => "Fecha:",
    "btn_guardar" => "Guardar",
    "link_ver_lista" => "Ver lista de tareas →",
    // Editar Tarea
    "editar_titulo" => "✏️ Editar Tarea",
    "msg_error_no_encontrada" => "❌ Error: Tarea no encontrada en la base de datos.",
    "label_titulo_edit" => "Título (Betreff):",
    "label_fach_edit" => "Asignatura / Categoría (Fach):",
    "categoria_antigua" => "(Categoría antigua)",
    "label_fecha_edit" => "Fecha Límite (Daten):",
    "label_desc_edit" => "Descripción (Beschreibung):",
    "btn_cancelar" => "❌ Cancelar",
    "btn_guardar_cambios" => "💾 Guardar Cambios",
    // Tareas Completadas
    "historial_titulo" => "Historial de Tareas",
    "h1_completadas" => "✅ Tareas Completadas",
    "info_completadas" => "Historial de tareas finalizadas. Se eliminarán automáticamente del servidor pasados 15 días.",
    "buscar_historial" => "🔍 Buscar tarea en el historial...",
    "completada_el" => "Completada el",
    "sin_descripcion" => "Sin descripción.",
    "btn_restaurar" => "♻️ Restaurar",
    "title_restaurar" => "Devolver a la Agenda principal",
    "btn_borrar" => "🗑️ Borrar",
    "title_borrar" => "Eliminar del servidor permanentemente",
    "msg_no_completadas" => "No hay tareas completadas en el historial reciente.",
    "btn_volver_agenda" => "⬅ Volver a la Agenda",
    "btn_ver_panel" => "📊 Ver Panel de Servidor",
    // Panel Servidor
    "msg_esperando_logs" => "Esperando registros... (O el usuario web no tiene permisos de lectura en access.log)",
    "msg_comando_ejecutado" => "🚀 Comando ejecutado:",
    "msg_no_encontrada" => "No encontrada",
    "msg_error" => "Error",
    "estado_titulo" => "BRAIN STATUS",
    "card_uptime" => "⏱️ Uptime",
    "card_ram" => "🧠 RAM Usage",
    "card_db" => "📁 Tamaño DB",
    "card_tareas" => "📝 Estado Tareas",
    "text_pendientes" => "Pendientes",
    "text_de" => "de",
    "text_totales" => "Totales",
    "title_live_log" => "📡 Server Live Log (Nginx Access)",
    "msg_cargando_logs" => "Cargando registros del servidor...",
    "title_disparador" => "🤖 Disparador Manual de Telegram",
    "desc_disparador" => "Ejecuta el script de Python para escanear las tareas pendientes y enviar las notificaciones individuales ahora mismo.",
    "btn_ejecutar_python" => "▶️ Ejecutar Python Script",
    "btn_pagina_principal" => "⬅ Página principal",
    "titulo_visualizar" => "Elegir Progreso",
    "h2_visualizar" => "¿Qué quieres visualizar?",
    "btn_peso_frente" => "Peso - Vista Frente",
    "btn_peso_perfil" => "Peso - Vista Perfil",
    "btn_musculo" => "Progreso Muscular",
];
?>