<?php
$lang = [
    // Navegació Global
    'titulo_index' => 'Main Brain',
    'menu_principal' => 'Menú Principal',
    'btn_agenda' => 'Agenda',
    'btn_personal' => 'Personal',
    'btn_academico' => 'Acadèmic',
    'btn_estado_server' => 'Estat del servidor',
    'inicio' => 'Inici',
    'volver' => 'Enrere',
    'volver_menu' => 'Tornar al Menú',
    'volver_personal' => 'Tornar a Personal',

    // Estat Server
    'estado_titulo' => 'Estat del Servidor',
    'msg_esperando_logs' => 'Esperant logs...',
    'msg_comando_ejecutado' => 'Executat correctament',
    'msg_no_encontrada' => 'No trobada',
    'msg_error' => 'Error',
    'card_uptime' => 'Temps Actiu',
    'card_ram' => 'Memòria RAM',
    'card_db' => 'Base de Dades',
    'card_tareas' => 'Tasques',
    'text_pendientes' => 'Pendents',
    'text_de' => 'de',
    'text_totales' => 'Totals',
    'title_live_log' => 'Logs d\'Accés en Viu',
    'msg_cargando_logs' => 'Carregant logs del sistema...',
    'title_disparador' => 'Disparador de Sistema',
    'desc_disparador' => 'Executar alertes manualment:',
    'btn_ejecutar_python' => 'Executar alertas.py',
    'btn_pagina_principal' => 'Pàgina Principal',

    // Menú Agenda
    'titulo_agenda_menu' => 'Recordatoris',
    'menu_acciones' => 'Accions d\'Agenda',
    'btn_crear_recordatorio' => 'Crear Recordatori',
    'btn_tareas_pendientes' => 'Tasques Pendents',
    'btn_tareas_completadas' => 'Tasques Completades',
    
    // Agenda: Formularis i Tasques
    'nueva_tarea_titulo' => 'Nova Tasca',
    'msg_error_db' => 'Error a la base de dades: ',
    'msg_fecha_pasado' => 'La data no pot estar en el passat.',
    'msg_tarea_guardada' => 'Tasca guardada amb èxit!',
    'label_titel' => 'Títol',
    'placeholder_titel' => 'Ex: Comprar pa',
    'label_descripcion' => 'Descripció',
    'placeholder_descripcion' => 'Detalls addicionals...',
    'label_fach' => 'Assignatura',
    'label_datum' => 'Data Límit',
    'btn_guardar' => 'Guardar Tasca',
    'link_ver_lista' => 'Veure llista de pendents',
    
    'editar_titulo' => 'Editar Tasca',
    'msg_error_no_encontrada' => 'La tasca sol·licitada no existeix.',
    'label_titulo_edit' => 'Títol de la tasca',
    'label_fach_edit' => 'Assignatura / Categoria',
    'categoria_antigua' => '(Antiga)',
    'label_fecha_edit' => 'Data programada',
    'label_desc_edit' => 'Descripció detallada',
    'btn_cancelar' => 'Cancel·lar',
    'btn_guardar_cambios' => 'Guardar Canvis',

    // Agenda: Llistes
    'historial_titulo' => 'Historial de Tasques',
    'h1_completadas' => 'Tasques Completades',
    'info_completadas' => 'Historial de totes les tasques finalitzades.',
    'buscar_historial' => 'Cercar a l\'historial...',
    'tarea' => 'Tasca',
    'asignatura' => 'Assignatura',
    'completada_el' => 'Completada el',
    'acciones' => 'Accions',
    'descripcion' => 'Descripció',
    'sin_descripcion' => 'Sense descripció addicional',
    'title_restaurar' => 'Tornar a pendents',
    'btn_restaurar' => 'Restaurar',
    'title_borrar' => 'Eliminar permanentment',
    'btn_borrar' => 'Esborrar',
    'msg_no_completadas' => 'Encara no hi ha tasques completades.',
    'btn_volver_agenda' => 'Tornar a l\'Agenda',
    'btn_ver_panel' => 'Veure Tauler',

    'titulo_lista' => 'Tasques Pendents',
    'boton_filtrar' => 'Filtrar',
    'boton_limpiar' => 'Netejar filtre',
    'buscar_placeholder' => 'Cercar una tasca ràpida...',
    'estado' => 'Estat',
    'fecha' => 'Data',
    'nueva_tarea' => 'Afegir Nova Tasca',

    // Àrea Personal
    'titulo_personal' => 'Àrea Personal',
    'btn_docs' => '📁 Documents i Resguards',
    'btn_ubermensch' => '🏋️‍♂️ Projecte Übermensch',
    'btn_proyectos_pers' => '💻 Projectes Personals',
    'btn_recuerdos' => '📸 Records i Fotos',

    // Projecte Übermensch
    'titulo_ubermensch' => 'Projecte Übermensch',
    'subtitulo_ubermensch' => 'Monitoratge de transformació física',
    'btn_visualizar_progreso' => 'Visualitzar Progrés',
    'btn_subir_progreso' => 'Pujar Nou Progrés',
    
    'titulo_visualizar' => 'Visualitzador de Progrés',
    'h2_visualizar' => 'Què vols visualitzar?',
    'btn_peso_frente' => 'Evolució Pes - Front',
    'btn_peso_perfil' => 'Evolució Pes - Perfil',
    'btn_musculo' => 'Progrés Muscular',
    
    'titulo_subir' => 'Pujar Fotos',
    'label_que_registrar' => 'Què vols registrar avui?',
    'label_selecciona_foto' => 'Selecciona la fotografia:',
    'btn_subir_foto' => 'Pujar Fotografia',
    'msg_progreso_exito' => 'Progrés registrat amb èxit!',
    'msg_progreso_error' => 'Error en guardar la foto. Revisa els permisos del servidor.',
    'msg_formato_invalido' => 'Format no vàlid. Utilitza només JPG, PNG o WEBP.',
    
    'titulo_presentacion' => 'Galeria d\'Evolució',
    'msg_categoria_invalida' => 'Categoria no vàlida o accés denegat per seguretat.',
    'msg_no_fotos' => 'Encara no has pujat fotografies a aquesta categoria.',
    'link_subir_primera' => 'Fes clic aquí per pujar la primera',
];
?>