<?php
$lang = [
    // Global Navigation
    'titulo_index' => 'Main Brain',
    'menu_principal' => 'Hauptmenü',
    'btn_agenda' => 'Agenda',
    'btn_personal' => 'Persönlich',
    'btn_academico' => 'Akademisch',
    'btn_estado_server' => 'Serverstatus',
    'inicio' => 'Startseite',
    'volver' => 'Zurück',
    'volver_menu' => 'Zurück zum Menü',
    'volver_personal' => 'Zurück zu Persönlich',

    // Server Status
    'estado_titulo' => 'Serverstatus Dashboard',
    'msg_esperando_logs' => 'Warten auf Logs...',
    'msg_comando_ejecutado' => 'Erfolgreich ausgeführt',
    'msg_no_encontrada' => 'Nicht gefunden',
    'msg_error' => 'Fehler',
    'card_uptime' => 'Betriebszeit',
    'card_ram' => 'Arbeitsspeicher',
    'card_db' => 'Datenbank',
    'card_tareas' => 'Aufgaben',
    'text_pendientes' => 'Ausstehend',
    'text_de' => 'von',
    'text_totales' => 'Gesamt',
    'title_live_log' => 'Live-Zugriffsprotokolle',
    'msg_cargando_logs' => 'Logs werden geladen...',
    'title_disparador' => 'System-Auslöser',
    'desc_disparador' => 'Warnungen manuell ausführen:',
    'btn_ejecutar_python' => 'alertas.py ausführen',
    'btn_pagina_principal' => 'Hauptseite',

    // Agenda Menu
    'titulo_agenda_menu' => 'Erinnerungen Machen',
    'menu_acciones' => 'Aktionen',
    'btn_crear_recordatorio' => 'Erinnerung erstellen',
    'btn_tareas_pendientes' => 'Ausstehende Aufgaben',
    'btn_tareas_completadas' => 'Abgeschlossene Aufgaben',
    
    // Agenda: Forms & Tasks
    'nueva_tarea_titulo' => 'Neue Aufgabe',
    'msg_error_db' => 'Datenbankfehler: ',
    'msg_fecha_pasado' => 'Das Datum darf nicht in der Vergangenheit liegen.',
    'msg_tarea_guardada' => 'Aufgabe erfolgreich gespeichert!',
    'label_titel' => 'Titel',
    'placeholder_titel' => 'Z.B.: Brot kaufen',
    'label_descripcion' => 'Beschreibung',
    'placeholder_descripcion' => 'Weitere Details...',
    'label_fach' => 'Fach',
    'label_datum' => 'Fälligkeitsdatum',
    'btn_guardar' => 'Speichern',
    'link_ver_lista' => 'Ausstehende Aufgaben ansehen',
    
    'editar_titulo' => 'Aufgabe bearbeiten',
    'msg_error_no_encontrada' => 'Aufgabe nicht gefunden',
    'label_titulo_edit' => 'Aufgabentitel',
    'label_fach_edit' => 'Fach / Kategorie',
    'categoria_antigua' => '(Alt)',
    'label_fecha_edit' => 'Geplantes Datum',
    'label_desc_edit' => 'Detaillierte Beschreibung',
    'btn_cancelar' => 'Abbrechen',
    'btn_guardar_cambios' => 'Änderungen speichern',

    // Agenda: Lists
    'historial_titulo' => 'Aufgabenverlauf',
    'h1_completadas' => 'Erledigte Aufgaben',
    'info_completadas' => 'Verlauf aller abgeschlossenen Aufgaben.',
    'buscar_historial' => 'Verlauf durchsuchen...',
    'tarea' => 'Aufgabe',
    'asignatura' => 'Fach',
    'completada_el' => 'Abgeschlossen am',
    'acciones' => 'Aktionen',
    'descripcion' => 'Beschreibung',
    'sin_descripcion' => 'Keine zusätzliche Beschreibung',
    'title_restaurar' => 'Wiederherstellen',
    'btn_restaurar' => 'Wiederherstellen',
    'title_borrar' => 'Dauerhaft löschen',
    'btn_borrar' => 'Löschen',
    'msg_no_completadas' => 'Noch keine abgeschlossenen Aufgaben.',
    'btn_volver_agenda' => 'Zurück zur Agenda',
    'btn_ver_panel' => 'Panel anzeigen',

    'titulo_lista' => 'Ausstehende Aufgaben',
    'boton_filtrar' => 'Filtern',
    'boton_limpiar' => 'Filter löschen',
    'buscar_placeholder' => 'Schnellsuche...',
    'estado' => 'Status',
    'fecha' => 'Datum',
    'nueva_tarea' => 'Neue Aufgabe hinzufügen',

    // Personal Area
    'titulo_personal' => 'Persönlicher Bereich',
    'btn_docs' => '📁 Dokumente und Belege',
    'btn_ubermensch' => '🏋️‍♂️ Projekt Übermensch',
    'btn_proyectos_pers' => '💻 Persönliche Projekte',
    'btn_recuerdos' => '📸 Erinnerungen & Fotos',

    // Übermensch Project
    'titulo_ubermensch' => 'Projekt Übermensch',
    'subtitulo_ubermensch' => 'Überwachung der physischen Transformation',
    'btn_visualizar_progreso' => 'Fortschritt anzeigen',
    'btn_subir_progreso' => 'Neuen Fortschritt hochladen',
    
    'titulo_visualizar' => 'Fortschrittsanzeige',
    'h2_visualizar' => 'Was möchtest du sehen?',
    'btn_peso_frente' => 'Gewichtsentwicklung - Frontal',
    'btn_peso_perfil' => 'Gewichtsentwicklung - Profil',
    'btn_musculo' => 'Muskelaufbau',
    
    'titulo_subir' => 'Fotos hochladen',
    'label_que_registrar' => 'Was möchtest du heute aufzeichnen?',
    'label_selecciona_foto' => 'Wähle das Foto aus:',
    'btn_subir_foto' => 'Foto hochladen',
    'msg_progreso_exito' => 'Fortschritt erfolgreich gespeichert!',
    'msg_progreso_error' => 'Fehler beim Speichern. Bitte Serverberechtigungen prüfen.',
    'msg_formato_invalido' => 'Ungültiges Format. Nur JPG, PNG oder WEBP erlaubt.',
    
    'titulo_presentacion' => 'Evolutionsgalerie',
    'msg_categoria_invalida' => 'Ungültige Kategorie oder Zugriff verweigert.',
    'msg_no_fotos' => 'Du hast noch keine Fotos in dieser Kategorie hochgeladen.',
    'link_subir_primera' => 'Klicke hier, um das erste hochzuladen',
];
?>