<?php
$lang = [
    // Global Navigation
    'titulo_index' => 'Main Brain',
    'menu_principal' => 'Main Menu',
    'btn_agenda' => 'Agenda',
    'btn_personal' => 'Personal',
    'btn_academico' => 'Academic',
    'btn_estado_server' => 'Server Status',
    'inicio' => 'Home',
    'volver' => 'Back',
    'volver_menu' => 'Back to Menu',
    'volver_personal' => 'Back to Personal',

    // Server Status
    'estado_titulo' => 'Server Status Dashboard',
    'msg_esperando_logs' => 'Waiting for logs...',
    'msg_comando_ejecutado' => 'Successfully executed',
    'msg_no_encontrada' => 'Not found',
    'msg_error' => 'Error',
    'card_uptime' => 'Uptime',
    'card_ram' => 'RAM Memory',
    'card_db' => 'Database',
    'card_tareas' => 'Tasks',
    'text_pendientes' => 'Pending',
    'text_de' => 'of',
    'text_totales' => 'Total',
    'title_live_log' => 'Live Access Logs',
    'msg_cargando_logs' => 'Loading system logs...',
    'title_disparador' => 'System Trigger',
    'desc_disparador' => 'Run manual alerts:',
    'btn_ejecutar_python' => 'Run alertas.py',
    'btn_pagina_principal' => 'Main Page',

    // Agenda Menu
    'titulo_agenda_menu' => 'Reminders',
    'menu_acciones' => 'Agenda Actions',
    'btn_crear_recordatorio' => 'Create Reminder',
    'btn_tareas_pendientes' => 'Pending Tasks',
    'btn_tareas_completadas' => 'Completed Tasks',
    
    // Agenda: Forms & Tasks
    'nueva_tarea_titulo' => 'New Task',
    'msg_error_db' => 'Database error: ',
    'msg_fecha_pasado' => 'The date cannot be in the past.',
    'msg_tarea_guardada' => 'Task saved successfully!',
    'label_titel' => 'Title',
    'placeholder_titel' => 'E.g.: Buy groceries',
    'label_descripcion' => 'Description',
    'placeholder_descripcion' => 'Additional details...',
    'label_fach' => 'Subject',
    'label_datum' => 'Due Date',
    'btn_guardar' => 'Save Task',
    'link_ver_lista' => 'View pending tasks',
    
    'editar_titulo' => 'Edit Task',
    'msg_error_no_encontrada' => 'Requested task not found.',
    'label_titulo_edit' => 'Task Title',
    'label_fach_edit' => 'Subject / Category',
    'categoria_antigua' => '(Old)',
    'label_fecha_edit' => 'Scheduled Date',
    'label_desc_edit' => 'Detailed Description',
    'btn_cancelar' => 'Cancel',
    'btn_guardar_cambios' => 'Save Changes',

    // Agenda: Lists
    'historial_titulo' => 'Task History',
    'h1_completadas' => 'Completed Tasks',
    'info_completadas' => 'History of all finished tasks.',
    'buscar_historial' => 'Search history...',
    'tarea' => 'Task',
    'asignatura' => 'Subject',
    'completada_el' => 'Completed on',
    'acciones' => 'Actions',
    'descripcion' => 'Description',
    'sin_descripcion' => 'No additional description',
    'title_restaurar' => 'Restore to pending',
    'btn_restaurar' => 'Restore',
    'title_borrar' => 'Delete permanently',
    'btn_borrar' => 'Delete',
    'msg_no_completadas' => 'No completed tasks yet.',
    'btn_volver_agenda' => 'Back to Agenda',
    'btn_ver_panel' => 'View Dashboard',

    'titulo_lista' => 'Pending Tasks',
    'boton_filtrar' => 'Filter',
    'boton_limpiar' => 'Clear filter',
    'buscar_placeholder' => 'Quick task search...',
    'estado' => 'Status',
    'fecha' => 'Date',
    'nueva_tarea' => 'Add New Task',

    // Personal Area
    'titulo_personal' => 'Personal Area',
    'btn_docs' => '📁 Documents & Receipts',
    'btn_ubermensch' => '🏋️‍♂️ Project Übermensch',
    'btn_proyectos_pers' => '💻 Personal Projects',
    'btn_recuerdos' => '📸 Memories & Photos',

    // Übermensch Project
    'titulo_ubermensch' => 'Project Übermensch',
    'subtitulo_ubermensch' => 'Physical transformation monitoring',
    'btn_visualizar_progreso' => 'View Progress',
    'btn_subir_progreso' => 'Upload New Progress',
    
    'titulo_visualizar' => 'Progress Viewer',
    'h2_visualizar' => 'What do you want to view?',
    'btn_peso_frente' => 'Weight Evolution - Front',
    'btn_peso_perfil' => 'Weight Evolution - Side',
    'btn_musculo' => 'Muscle Progress',
    
    'titulo_subir' => 'Upload Photos',
    'label_que_registrar' => 'What will you record today?',
    'label_selecciona_foto' => 'Select the photo:',
    'btn_subir_foto' => 'Upload Photo',
    'msg_progreso_exito' => 'Progress recorded successfully!',
    'msg_progreso_error' => 'Error saving photo. Check server permissions.',
    'msg_formato_invalido' => 'Invalid format. Use only JPG, PNG, or WEBP.',
    
    'titulo_presentacion' => 'Evolution Gallery',
    'msg_categoria_invalida' => 'Invalid category or access denied.',
    'msg_no_fotos' => 'You haven\'t uploaded any photos to this category yet.',
    'link_subir_primera' => 'Click here to upload the first one',
];
?>