<?php
$lang = [
    // Navegación Global
    'titulo_index' => 'Main Brain',
    'menu_principal' => 'Menú Principal',
    'btn_agenda' => 'Agenda',
    'btn_personal' => 'Personal',
    'btn_academico' => 'Académico',
    'btn_estado_server' => 'Estado del servidor',
    'inicio' => 'Inicio',
    'volver' => 'Atrás',
    'volver_menu' => 'Volver al Menú',
    'volver_personal' => 'Volver a Personal',

    // Estado Server
    'estado_titulo' => 'Estado del Servidor',
    'msg_esperando_logs' => 'Esperando logs...',
    'msg_comando_ejecutado' => 'Ejecutado correctamente',
    'msg_no_encontrada' => 'No encontrada',
    'msg_error' => 'Error',
    'card_uptime' => 'Tiempo Activo',
    'card_ram' => 'Memoria RAM',
    'card_db' => 'Base de Datos',
    'card_tareas' => 'Tareas',
    'text_pendientes' => 'Pendientes',
    'text_de' => 'de',
    'text_totales' => 'Totales',
    'title_live_log' => 'Logs de Acceso en Vivo',
    'msg_cargando_logs' => 'Cargando logs del sistema...',
    'title_disparador' => 'Disparador de Sistema',
    'desc_disparador' => 'Ejecutar alertas manualmente:',
    'btn_ejecutar_python' => 'Ejecutar alertas.py',
    'btn_pagina_principal' => 'Página Principal',

    // Menú Agenda
    'titulo_agenda_menu' => 'Recordatorios',
    'menu_acciones' => 'Acciones de Agenda',
    'btn_crear_recordatorio' => 'Crear Recordatorio',
    'btn_tareas_pendientes' => 'Tareas Pendientes',
    'btn_tareas_completadas' => 'Tareas Completadas',
    
    // Agenda: Formularios y Tareas
    'nueva_tarea_titulo' => 'Nueva Tarea',
    'msg_error_db' => 'Error en la base de datos: ',
    'msg_fecha_pasado' => 'La fecha no puede estar en el pasado.',
    'msg_tarea_guardada' => '¡Tarea guardada con éxito!',
    'label_titel' => 'Título',
    'placeholder_titel' => 'Ej: Estudiar redes',
    'label_descripcion' => 'Descripción',
    'placeholder_descripcion' => 'Detalles adicionales...',
    'label_fach' => 'Asignatura',
    'label_datum' => 'Fecha Límite',
    'btn_guardar' => 'Guardar Tarea',
    'link_ver_lista' => 'Ver lista de pendientes',
    
    'editar_titulo' => 'Editar Tarea',
    'msg_error_no_encontrada' => 'La tarea solicitada no existe.',
    'label_titulo_edit' => 'Título de la tarea',
    'label_fach_edit' => 'Asignatura / Categoría',
    'categoria_antigua' => '(Antigua)',
    'label_fecha_edit' => 'Fecha programada',
    'label_desc_edit' => 'Descripción detallada',
    'btn_cancelar' => 'Cancelar',
    'btn_guardar_cambios' => 'Guardar Cambios',

    // Agenda: Listas
    'historial_titulo' => 'Historial de Tareas',
    'h1_completadas' => 'Tareas Completadas',
    'info_completadas' => 'Historial de todas las tareas finalizadas.',
    'buscar_historial' => 'Buscar en el historial...',
    'tarea' => 'Tarea',
    'asignatura' => 'Asignatura',
    'completada_el' => 'Completada el',
    'acciones' => 'Acciones',
    'descripcion' => 'Descripción',
    'sin_descripcion' => 'Sin descripción adicional',
    'title_restaurar' => 'Devolver a pendientes',
    'btn_restaurar' => 'Restaurar',
    'title_borrar' => 'Eliminar permanentemente',
    'btn_borrar' => 'Borrar',
    'msg_no_completadas' => 'Aún no hay tareas completadas.',
    'btn_volver_agenda' => 'Volver a la Agenda',
    'btn_ver_panel' => 'Ver Panel',

    'titulo_lista' => 'Tareas Pendientes',
    'boton_filtrar' => 'Filtrar',
    'boton_limpiar' => 'Limpiar filtro',
    'buscar_placeholder' => 'Buscar una tarea rápida...',
    'estado' => 'Estado',
    'fecha' => 'Fecha',
    'nueva_tarea' => 'Añadir Nueva Tarea',

    // Área Personal
    'titulo_personal' => 'Área Personal',
    'btn_docs' => '📁 Documentos y Resguardos',
    'btn_ubermensch' => '🏋️‍♂️ Proyecto Übermensch',
    'btn_proyectos_pers' => '💻 Proyectos Personales',
    'btn_recuerdos' => '📸 Recuerdos y Fotos',

    // Proyecto Übermensch
    'titulo_ubermensch' => 'Proyecto Übermensch',
    'subtitulo_ubermensch' => 'Monitoreo de transformación física',
    'btn_visualizar_progreso' => 'Visualizar Progreso',
    'btn_subir_progreso' => 'Subir Nuevo Progreso',
    
    'titulo_visualizar' => 'Visualizador de Progreso',
    'h2_visualizar' => '¿Qué quieres visualizar?',
    'btn_peso_frente' => 'Evolución Peso - Frente',
    'btn_peso_perfil' => 'Evolución Peso - Perfil',
    'btn_musculo' => 'Progreso Muscular',
    
    'titulo_subir' => 'Subir Fotos',
    'label_que_registrar' => '¿Qué quieres registrar hoy?',
    'label_selecciona_foto' => 'Selecciona la fotografía:',
    'btn_subir_foto' => 'Subir Fotografía',
    'msg_progreso_exito' => '¡Progreso registrado con éxito!',
    'msg_progreso_error' => 'Error al guardar la foto. Revisa los permisos del servidor.',
    'msg_formato_invalido' => 'Formato no válido. Utiliza solo JPG, PNG o WEBP.',
    
    'titulo_presentacion' => 'Galería de Evolución',
    'msg_categoria_invalida' => 'Categoría no válida o acceso denegado por seguridad.',
    'msg_no_fotos' => 'Aún no has subido fotografías a esta categoría.',
    'link_subir_primera' => 'Haz clic aquí para subir la primera',
];
?>